[package]
name = "rodalies-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive", "unicode"] }
surf = { version = "2.3", features = ["h1-client"] }
tokio = { version = "1.18", features = ["full"] }
scraper = "0.13"
itertools = "0.10"
chrono = "0.4"
prettytable-rs = "0.8"
